@Mype.Api_HostAddress = http://localhost:5010

GET {{Mype.Api_HostAddress}}/health
Accept: application/json

###

POST {{Mype.Api_HostAddress}}/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
  "displayName": "Usuario de prueba",
  "email": "usuario@dominio.com",
  "password": "password1",
  "passwordConfirmation": "password1"
}

###

POST {{Mype.Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "usuario@dominio.com",
  "password": "password1"
}

###