name: Deploy
on:
  workflow_run:
    workflows: ["Quality"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore Mype/Mype.slnx

      - name: Publish
        run: |
          dotnet publish Mype/src/Mype.Api/Mype.Api.csproj \
            -c Release \
            --no-restore \
            -o ./publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@5cfb776471c748b351e1ebf5770e208a54ace016
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
